# Generated by Django 4.1.5 on 2023-02-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=256)),
                ("desc", models.CharField(max_length=300)),
                ("pub_date", models.DateField()),
            ],
        ),
    ]
